# Generated by Django 4.2.1 on 2023-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
