# Generated by Django 4.2.1 on 2023-06-01 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0007_alter_card_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
