# Generated by Django 4.2.1 on 2023-06-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0011_alter_card_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image',
            new_name='ppic',
        ),
    ]
