# Generated by Django 4.2.1 on 2023-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0012_rename_image_card_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ppic',
            field=models.ImageField(default='', upload_to='../static/images/'),
        ),
    ]
