# Generated by Django 4.2.1 on 2023-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0014_alter_card_ppic'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.FloatField(default=int),
        ),
    ]
