# Generated by Django 4.2.1 on 2023-06-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0016_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
