# Generated by Django 4.2.1 on 2023-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0017_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_query', models.CharField(max_length=30)),
            ],
        ),
    ]
